# Generated by Django 4.2.5 on 2023-10-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listing", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userfollows",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
