# Generated by Django 4.2.5 on 2023-10-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listing", "0002_alter_userfollows_unique_together_alter_ticket_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="visibility",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="visibility",
            field=models.BooleanField(default=True),
        ),
    ]
