# Generated by Django 3.1.4 on 2023-11-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_alter_subscription_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='critique',
            field=models.BooleanField(default=False),
        ),
    ]
